server:
  port: 8484
  
spring:
  application:
    name: API_GATEWAY
    
  cloud:
    gateway:
      routes:
       - id: PATIENT_SERVICE
         uri: lb://PATIENT_SERVICE
         predicates:
               - path=/patient/getpat/**
        
       - id: DOCTOR_SERVICE
         uri: lb://DOCTOR_SERVICE
         predicates:
                - path=/doctor/getdoc/**
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
          
        
          
         
  